### ISSUE TITLE
search is not working

### ISSUE THREAD

**Issue by nuevoleonkx** [Hironsan/bertsearch#16]

**Comment by iceriver97** [comment]
Hello, I also encountered the same problem, have you solved it?

**Comment by nuevoleonkx** [comment]
Yes but it was my mistake.. 
1. ensure you have the same version of bert client/server (in order to create the connection propperly) when I look into the log, the server were not creating because the version differs
2. make sure your elastic connection parameters are correct server, index 
3. You will get the almost the same results if your index contain small number of documents (ensure you have a large number of documents because otherwise the rank will be pretty close the same)
