### ISSUE TITLE
This does not work

### ISSUE THREAD

**Issue by KlausSchaefers** [Hironsan/bertsearch#27]
When I follow the steps in the readme, I get the following error:

Traceback (most recent call last):
web_1            |   File "/app/app.py", line 5, in <module>
web_1            |     from elasticsearch import Elasticsearch
web_1            |   File "/usr/local/lib/python3.9/site-packages/elasticsearch/__init__.py", line 24, in <module>
web_1            |     from .client import Elasticsearch
web_1            |   File "/usr/local/lib/python3.9/site-packages/elasticsearch/client/__init__.py", line 4, in <module>
web_1            |     from ..transport import Transport
web_1            |   File "/usr/local/lib/python3.9/site-packages/elasticsearch/transport.py", line 5, in <module>
web_1            |     from .connection import Urllib3HttpConnection
web_1            |   File "/usr/local/lib/python3.9/site-packages/elasticsearch/connection/__init__.py", line 2, in <module>
web_1            |     from .http_requests import RequestsHttpConnection
web_1            |   File "/usr/local/lib/python3.9/site-packages/elasticsearch/connection/http_requests.py", line 3, in <module>
web_1            |     from base64 import decodestring
web_1            | ImportError: cannot import name 'decodestring' from 'base64' (/usr/local/lib/python3.9/base64.py)

**Comment by ssanjoris** [comment]
I get the following error , when I follow the steps:
and the flask web is failing to start.

Traceback (most recent call last):
  File "app.py", line 4, in <module>
    from flask import Flask, render_template, jsonify, request
  File "/usr/local/lib/python3.8/site-packages/flask/__init__.py", line 14, in <module>
    from jinja2 import escape
ImportError: cannot import name 'escape' from 'jinja2' (/usr/local/lib/python3.8/site-packages/jinja2/__init__.py)
