### ISSUE TITLE
'docker-compose up' version error

### ISSUE THREAD

**Issue by albertKg** [Hironsan/bertsearch#29]
Hi,
some error happen in very begining with docker-compose.
Looks like your version of compose is quite old from default version 3.8
Do we have chance use this version here?

Thanks a lot for advance!

How to reproduce the problem
---------

```bash  docker-compose up```
ERROR: Version in "./docker-compose.yaml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/

My Environment
---------

*   Operating System: Ubuntu 18
*   docker version: 19.03.13, 
*   docker-compose version:   1.17.1

**Comment by Hironsan** [comment]
It seems to me that your docker-compose version 1.17.1 is old. The version supports compose file version 3.4:

- [Docker Compose 1.17.0](https://docs.docker.com/compose/release-notes/#1170)

Please update it.

**Comment by chengyuliu-cs** [comment]
I had the same issue. 

It would be good and could have saved some time for users if there are detailed requirements, for example, docker compose version.
