### ISSUE TITLE
Cannot create_documents

### ISSUE THREAD

**Issue by assist726** [Hironsan/bertsearch#5]
@Hironsan I have a similar issue as a previous ticket where the create_documents.py command hangs for a long time and is unable to create the documents.jsonl

I have confirmed that my docker containers are correctly running and bert-server is up.

I have tried debugging the script to no avail, could you just clarify that it is indeed functional?

**Comment by assist726** [comment]
@Hironsan

**Comment by Hironsan** [comment]
Could you create documents.jsonl for example.csv?

**Comment by assist726** [comment]
@Hironsan  running the following command results in it just hanging permanently : 

```
python example/create_documents.py --data=example/example.csv --index_name=jobsearch
```

**Comment by Hironsan** [comment]
@assist726 Please tell me your Docker's memory configuration.
If possible, assign more memory(more than 8GB).
Because BERT container needs high memory.

**Comment by assist726** [comment]
@Hironsan Much appreciated! Works fine now.

Would recommend this being suggested in the README
