### ISSUE TITLE
No output in the html file

### ISSUE THREAD

**Issue by laifuchicago** [Hironsan/bertsearch#6]
Hello, Hironsan. We have tried your manual, but we are stuck at the webapi.py , the error is the index problem just like this 

Traceback (most recent call last):
web_1            |   File "app.py", line 8, in <module>
web_1            |     INDEX_NAME = os.environ['INDEX_NAME']
web_1            |   File "/usr/local/lib/python3.8/os.py", line 673, in __getitem__
web_1            |     raise KeyError(key) from None
web_1            | KeyError: 'INDEX_NAME'

and there is no output on html , can you please help us?
Thank you !

**Comment by Hironsan** [comment]
Did you set INDEX_NAME as an environment variable？
https://github.com/Hironsan/bertsearch#2-set-environment-variables

**Comment by laifuchicago** [comment]
Yes, I tried, and got this picture below.
 Thank you

Hiroki Nakayama <notifications@github.com> 於 2019年11月15日 週五 下午5:33寫道：

**Comment by laifuchicago** [comment]
![failure](https://user-images.githubusercontent.com/8537280/69004450-6da74800-094e-11ea-8485-fd98143cb060.JPG)
