### ISSUE TITLE
Can I search with sentence ?

### ISSUE THREAD

**Issue by laifuchicago** [Hironsan/bertsearch#7]
To: Hironsan
          I just tried to follow your steps, and everything was fine. I have two questions:
(1)if I want to ask questions of the topic, can it give me the certain sentence, not the whole paragraph ?
(2) Can it executed on Internet(such as Google Search) instead of localhost?

Jonathan

**Comment by tholor** [comment]
This sounds to me rather like a question answering task than search (Input: Question, Output: answer = a few words from a paragraph). If that's the case, it might be interesting for you to have a look at https://github.com/deepset-ai/haystack
